name: Testing simdjson PHP extension
on: [push, pull_request]

env:
  NO_INTERACTION: 1

jobs:
  PHP74-alpine:
    name: PHP 7.4 Alpine 3.12
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Build extension"
        run: "docker build -t simdjsontest -f docker_php7.4-alpine ."

      - name: "Show"
        run: "docker run --rm simdjsontest php --ri simdjson"

  Ubuntu:
    name: "PHP"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.4.1"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Build extension"
        run: |
          phpize${{ matrix.php-version }}
          ./configure
          sudo make
          sudo make install
          sudo make test

      - name: "Show"
        run: "php -dextension=simdjson.so --ri simdjson"

      - name: "Error log"
        if: ${{ failure() }}
        run: "ls -1t tests/*.log | xargs -d'\n' cat"